"""Protocol definitions for orbit canvases."""

from __future__ import annotations

from typing import Protocol

from .models import MassParameters, OrbitParameters


class OrbitCanvas(Protocol):
    """Minimal surface area MainWindow needs from a canvas."""

    def apply_parameters(self, params: OrbitParameters, *, keep_phase: bool) -> None: ...

    def apply_masses(self, masses: MassParameters) -> None: ...

    def update_all(self) -> None: ...

    def recompute_mean_motion(self) -> None: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...

    def lock_axes(self, lock: bool = True, L: float | None = None) -> None: ...

    def set_limits(self, L: float) -> None: ...

    def set_ticks(self, count2d: int | None = None, count3d: int | None = None, step2d: float | None = None, prune_ends: bool = True) -> None: ...

    def apply_font_size(self, size: int, *, redraw: bool = True) -> None: ...

    def set_arc_epsilon(self, eps: float) -> None: ...